import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './components/Footer'
import Navbar from './components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Codeswear',
  description: 'Generated by using nextjs framework',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
